server:
  port: 9010

spring:
  application:
    name: keycloak-user-details-service
  datasource:
    url: jdbc:postgresql://postgres:5432/keycloak
    username: keycloak
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: rg.hibernate.dialect.PostgreSQLDialect
